apiVersion: v1
kind: Secret
metadata:
  name: nplus-test-secret
  namespace: apigw
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    <your-cert-pem>
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    <your-key-pem>
    -----END RSA PRIVATE KEY-----

